travis:
  secure:
    BINSTAR_TOKEN: aCvGd7iTMCHI1k9gsOLhsmGR3epFaazbyzxFkPHwDUPx5+iTzNwEvf4KOFJIGEIq3j6z7Dkr4BBQvvkCfV9dJwMbAYKvSQOb0HR66SNC1711Xu6Mqg8Iymzy2f23WbzBNjNbdRSr0vZb5iSYFwkojj7+M6jYNAxPbGAeq/+pVr8XR8TBRsWJ7I0n2Kjz9H3HghtA3FMwmqB0XPtrqo/4ATxXPHciPbTV9pDqhbiJnu3LLLS6q6xssCGxlNyAd+MNHZXGC0KiHsbtqyojpNcsyVeKxgwQfYZidvEhk1/EfBDbKjByxFhchktYA7VzE8zr4bMfy/4WuQ3Ncyc/I+KDHdfZi3ALnVFR/cQos0T58AlvJI0vS9+etVwS+YDufq9S6h8dnpTMCS52nwrg2PDfvn1ufcz6VcrPjDF9DjuvH+mYueDsBbkx4bqm4XkgVWpVOtH/NUv4QtsO+bglHM/QNvGEJSiTtBlO/625yZWTgzTQn5bPwkln0J46V0lGaKB/+T5EJLfgJB+Uj6NB5OOYZhE/1iBb78I79ftCA8uJIrI2H5ZdnZJFPb8pluelcb5LUXNpILIaB5sV1XHFN/eZXyGNJjfPpBKZBLXbVnizE0Tz/tgIKoy/o8td6hycQQLG72bkKdXP77FIEfJIGxGAEz7ETBeylMMrn/O5WlLbkB8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
